<a href="https://colab.research.google.com/github/moxie77/Data_preprocessing/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#uploading the file
from google.colab import files
upload = files.upload()

Saving Data.csv to Data (3).csv


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [3]:
Data = pd.read_csv("Data.csv")

In [4]:
Data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [5]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [6]:
x = Data[['Country','Age','Salary']]
y = Data[['Purchased']]

In [7]:
y

Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes

In [8]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [9]:
Data.groupby('Country').mean()

Age        Salary
Country                    
France   41.0  69000.000000
Germany  40.0  68500.000000
Spain    32.5  53666.666667

In [10]:
#Missing Data
def get_avg_salary(col):
  col_1 = col[0]
  col_2 = col[1]
  if pd.isnull(col_1):
    if col_2 == "France":
      return 69000.0
    elif col_2 == "Germany":
      return 68500.0
    else:
      return 53666.6
  else:
    return col_1

In [11]:
def get_avg_age(col):
  col_1 = col[0]
  col_2 = col[1]
  if pd.isnull(col_1):
    if col_2 == "France":
      return 41.0
    elif col_2 == "Germany":
      return 40.0
    else:
      return 32.5
  else:
    return col_1

In [12]:
x['Age'] = x[['Age', 'Country']].apply(get_avg_age, axis=1)
x['Salary'] = x[['Salary', 'Country']].apply(get_avg_salary, axis=1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [13]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0  68500.0
5   France  35.0  58000.0
6    Spain  32.5  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [14]:
import sklearn

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [16]:
x

array([[1.00e+00, 0.00e+00, 0.00e+00, 4.40e+01, 7.20e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.70e+01, 4.80e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.00e+01, 5.40e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.80e+01, 6.10e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.00e+01, 6.85e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.50e+01, 5.80e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.25e+01, 5.20e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.80e+01, 7.90e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.00e+01, 8.30e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.70e+01, 6.70e+04]])

In [17]:
y = pd.get_dummies(y, drop_first=True)

In [20]:
y = np.array(y)

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1)

In [23]:
x_test

array([[0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04]])

In [24]:
x_train

array([[0.00e+00, 0.00e+00, 1.00e+00, 3.25e+01, 5.20e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.00e+01, 6.85e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.40e+01, 7.20e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.80e+01, 6.10e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.70e+01, 4.80e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.80e+01, 7.90e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.00e+01, 8.30e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.50e+01, 5.80e+04]])

In [25]:
y_train

array([[0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1]], dtype=uint8)

In [26]:
y_test

array([[0],
       [1]], dtype=uint8)

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [29]:
x_train

array([[ 0.        ,  0.        ,  1.        , -0.92871122, -1.12261044],
       [ 0.        ,  1.        ,  0.        ,  0.09372315,  0.28198272],
       [ 1.        ,  0.        ,  0.        ,  0.63902148,  0.57992672],
       [ 0.        ,  0.        ,  1.        , -0.17892602, -0.35646872],
       [ 0.        ,  0.        ,  1.        , -1.67849643, -1.46311787],
       [ 1.        ,  0.        ,  0.        ,  1.18431982,  1.17581472],
       [ 0.        ,  1.        ,  0.        ,  1.45696898,  1.51632216],
       [ 1.        ,  0.        ,  0.        , -0.58789977, -0.61184929]])

In [30]:
x_test

array([[ 0.        ,  1.        ,  0.        , -1.26952268, -0.95235672],
       [ 1.        ,  0.        ,  0.        , -0.3152506 ,  0.15429243]])